- cernopendata_client/cli.py
* Closes #5
* Closes #6
* Closes #7
> cli: incorrect options don't fall back to recid=1

- MANIFEST.in
- run-tests.sh
- setup.py
* Adds MANIFEST for the future Python package release.
* Enables manifest checking in CI procedures.
Signed-off-by: Tibor Šimko <tibor.simko@cern.ch>
> installation: manifest

- cernopendata_client/cli.py
* Adds new option expand/no-expand to expand file_index.txt
into list of individual data locations. (closes #9)
Signed-off-by: Adam Novorolnik <adam.novorolnik@gmail.com>
> get-file-locations: expands index files

- AUTHORS.rst
- cernopendata_client/cli.py
> cli: fix get-record by doi

- cernopendata_client/validator.py
- run-tests.sh
- setup.cfg
- setup.py
- tests/test_validator.py
Confiigures and plug pytest and coverage.
Provides example for `validator()` tests.
Addresses #33.
> Tests validate

- .travis.yml
- cernopendata_client/cli.py
- cernopendata_client/search.py
- cernopendata_client/tui.py
- setup.py
- tests/tests_cli/test_download_files.py
- tests/tests_cli/test_get_file_locations.py
- tests/tests_cli/test_get_record.py
> cli: download files feature

- cernopendata_client/cli.py
- cernopendata_client/downloader.py
- docs/usage.rst
- tests/test_cli_download_files.py
> cli: download-files - prettify progress bar display

- cernopendata_client/validator.py
- tests/test_cli_download_files.py
- tests/test_validator.py
> tests: download-files filters using recid 5500

- cernopendata_client/cli.py
- tests/test_cli_get_metadata.py
> cli: get-metadata: expose only metadata

- cernopendata_client/cli.py
- cernopendata_client/search.py
- docs/usage.rst
- tests/test_cli_get_metadata.py
closes #41
- Added searching of fields in nested json
- Added tests and docs
> cli: get-metadata - amend `--output-fields` behaviour

- cernopendata_client/cli.py
- cernopendata_client/downloader.py
- cernopendata_client/searcher.py
- cernopendata_client/utils.py
- cernopendata_client/validator.py
- cernopendata_client/verifier.py
- run-tests.sh
- setup.cfg
> docs: introduce pydocstyle

- cernopendata_client/cli.py
- cernopendata_client/config.py
- cernopendata_client/searcher.py
> config: Added SERVER variable

- .github/workflows/ci.yml
- run-tests.sh
> ci: add shellcheck and improve run-tests script

- .github/workflows/ci.yml
- cernopendata_client/cli.py
- cernopendata_client/searcher.py
- docs/usage.rst
> cli: download-files --verify each file as they are downloaded

- cernopendata_client/cli.py
- cernopendata_client/config.py
- cernopendata_client/downloader.py
- cernopendata_client/printer.py
- cernopendata_client/searcher.py
- cernopendata_client/utils.py
- cernopendata_client/validator.py
- cernopendata_client/verifier.py
- tests/test_cli_download_files.py
- replace `print()` and `click.echo()` with `display_message()`
closes #61
> cli: printer initial release

- cernopendata_client/cli.py
- cernopendata_client/utils.py
- cernopendata_client/validator.py
- tests/test_cli_download_files.py
- tests/test_cli_get_metadata.py
- tests/test_cli_verify_files.py
- tests/test_utils.py
- tests/test_validator.py
> cli: show error messages instead of python tracebacks

- cernopendata_client/cli.py
- cernopendata_client/printer.py
- cernopendata_client/searcher.py
- cernopendata_client/validator.py
- pytest.ini
- tests/test_cli_download_files.py
- tests/test_cli_get_metadata.py
- tests/test_cli_verify_files.py
- tests/test_validator.py
- tests/test_verifier.py
- tests/test_version.py
> tests: complete code coverage

- .github/workflows/ci.yml
- Dockerfile
- cernopendata_client/cli.py
- cernopendata_client/downloader.py
- cernopendata_client/searcher.py
- docs/usage.rst
- setup.py
- tests/test_cli_download_files.py
> cli: download-files - xrootd protocol

- Dockerfile
- cernopendata_client/downloader.py
- setup.py
- tests/test_cli_download_files.py
Added pycurl as optional dependency
closes #78
> cli: download-files with http protocol using requests

- cernopendata_client/cli.py
- docs/cliapi.rst
- docs/conf.py
- docs/requirements.txt
- setup.py
> docs: enrich CLI API page

- cernopendata_client/cli.py
- cernopendata_client/downloader.py
- cernopendata_client/searcher.py
- docs/installation.rst
- docs/usage.rst
- setup.py
- tests/test_cli_download_files.py
> docs: mention xrootd and pycurl installation options

- cernopendata_client/cli.py
- cernopendata_client/config.py
- cernopendata_client/downloader.py
- cernopendata_client/searcher.py
- docs/usage.rst
- tests/test_cli_download_files.py
> protocol: add 'https' option

- cernopendata_client/cli.py
- cernopendata_client/config.py
- cernopendata_client/searcher.py
- cernopendata_client/validator.py
- docs/cliapi.rst
- docs/usage.rst
- tests/test_cli_list_directory.py
- tests/test_validator.py
> cli: add list-directory command

- cernopendata_client/cli.py
- cernopendata_client/searcher.py
- cernopendata_client/validator.py
- docs/usage.rst
- tests/test_cli_get_file_locations.py
- tests/test_validator.py
> cli: get-file-locations --verbose option

- .github/workflows/ci.yml
- Dockerfile
- run-tests.sh
Installs XRootD command-line client.
Simplifies build instructions and removes unnecessary packages to make
the image slimmer.
Improves Dockerfile linting and adds a new CI check.
> docker: XRootD client and build simplification

- cernopendata_client/cli.py
- cernopendata_client/downloader.py
- cernopendata_client/searcher.py
- docs/cliapi.rst
- docs/installation.rst
- docs/usage.rst
Improves verbiage and formatting of the user documentation.
Harmonises help messages for command-line options.
Fixes spelling of the usual unit symbol for kibibytes (KiB).
> docs: formatting improvements

- cernopendata_client/cli.py
- cernopendata_client/searcher.py
- cernopendata_client/walker.py
> searcher: separate out get_list_directory() and friends

- cernopendata_client/cli.py
- cernopendata_client/searcher.py
- tests/test_cli_get_file_locations.py
> cli: Improve --verbose functionality

- CHANGES.rst
- cernopendata_client/version.py
- docs/cliapi.rst
Note: to be merged after #94 and #97 are addressed.
> release: 0.2.0

- cernopendata_client/walker.py
> walker: enrich output with parent directories

- cernopendata_client/cli.py
- cernopendata_client/searcher.py
- tests/test_cli_get_file_locations.py
> searcher: simplify protocol notion

- .github/workflows/ci.yml
- cernopendata_client/searcher.py
- tests/test_cli_get_file_locations.py
> searcher: add KeyError handling and test case

- cernopendata_client/downloader.py
Add resume downloads for `pycurl` library
addresses #99
> downloader: resume interrupted downloads

- .editorconfig
- .github/workflows/ci.yml
- .markdownlint.yaml
- .prettierrc.yaml
- .release-please-config.json
- .yamllint.yaml
- CHANGELOG.md
- CONTRIBUTING.md
- MANIFEST.in
- README.md
- docs/authors.md
- docs/changes.md
- docs/contributing.md
- docs/installation.md
- docs/license.md
- docs/usage.md
- run-tests.sh
- ci(run-tests): add usage help and refactor options
- ci(jsonlint): add JSON linting
- ci(shfmt): add shfmt code formatting checks
- ci(prettier): add Prettier code formatting checks
- ci(markdownlint): add Markdown linting
- ci(yamllint): add YAML linting
> ci(run-tests): add usage help and refactor options
